### ISSUE TITLE
The UART_to_BLE_central doesn't seem to open in PSoC Creator 3.1

### ISSUE THREAD

**Issue by junkforjeff** [cypresssemiconductorco/PSoC-4-BLE#1]
Downloaded latest PSoC Creator for the CY8CKIT-042-BLE (as of 4/6/2015) and when I open the UART_to_BLE project I get the following message:

Error: sdb.M0020: Error in customizer for component "BLE_v1_20" : Loading : (Unable to locate and customize component 'BLE_v1_20' used in schematic '...\Cypress\PSoC-4-BLE-master\PSoC-4-BLE-master\100_Projects_in_100_Days\Day020_BLE_UART\UART_to_BLE_central\UART_to_BLE_central.cydsn\TopDesign\TopDesign.cysch'.).
 CANCEL

The Heart Rate project seems to open correctly so I'm assuming the tools are set up correctly?

**Comment by junkforjeff** [comment]
For some reason the downloaded version installed older parts of BLE, fixed by updating..

**Comment by TheFearlessTinkerer** [comment]
Got the same error with PSoc Creator 3.3 SP2. What exactly did you update to fix this?

**Comment by TheFearlessTinkerer** [comment]
Never mind. It's Project->Update Components, just as the detailed error message recommends :-)

**Comment by soulne4ny** [comment]
Project->Update Components works.
