### ISSUE TITLE
Day010_Observer - advReport.data prints incorrectly

### ISSUE THREAD

**Issue by svvagga** [cypresssemiconductorco/PSoC-4-BLE#10]
main.c - The for loop at lines 167 to 170 or printf within should be corrected as the first value printed is outside of the `advReport.data` array.

`advReport.data[advReport.dataLen-i]`will always do this when i = 0.

Thanks :)

**Comment by JimTrudeau** [comment]
My apologies that years ago it appears no one was paying attention to issues on Cypress GitHub. I am closing this issue as moot.
