### ISSUE TITLE
Day024_Throughput/Throughput/GATT Notification - Data Outgoing.cydsn/main.c - deprecated function

### ISSUE THREAD

**Issue by Papiertig0r** [cypresssemiconductorco/PSoC-4-BLE#12]
Line 258 states:
`CyBle_GattGetBusStatus() == CYBLE_STACK_STATE_FREE`

but the documentation in
BLE_1_eventHandler.h states in line 2418:
`/* Deprecated macro name. Not recommended for use in new design */`
`#define CyBle_GattGetBusStatus  CyBle_GattGetBusyStatus`

**Comment by JimTrudeau** [comment]
My apologies that years ago it appears no one was paying attention to issues on Cypress GitHub. I am closing this issue as moot.
