### ISSUE TITLE
Day020_BLE_UART

### ISSUE THREAD

**Issue by soulne4ny** [cypresssemiconductorco/PSoC-4-BLE#13]
Hi,

I'm using CySmart on iPhone to try to talk to BLE UART project running on CY8CKIT-042-BLE PIONEER KIT. CySmart shows there is a notify-characteristic and a write-characteristic. Writing something to write-characteristic, I get it on UART console. Typing anything on console, does not produce any effect on notify-characteristic.

What could be wrong there?

**Comment by soulne4ny** [comment]
Here [UART_to_BLE_peripheral.cydsn/app_UART.c#L57](https://github.com/cypresssemiconductorco/PSoC-4-BLE/blob/master/100_Projects_in_100_Days/Day020_BLE_UART/UART_to_BLE_peripheral/UART_to_BLE_peripheral.cydsn/app_UART.c#L57) it does never see `uartTxDataLength > 0`.

**Comment by jkumeboshi** [comment]
It works with CySmart and USB dongle on PC?

**Comment by JimTrudeau** [comment]
I am closing this issue as moot.
