### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by oxr463** [cypresssemiconductorco/PSoC-4-BLE#24]
What license do these samples fall under? It would be helpful to include this in the README, which would also be nice to have too!

**Comment by JimTrudeau** [comment]
My apologies that no one has answered this before now. I'm fixing that problem. 

These projects are governed by the information in each main.c or other source file, which describes the copyright or license details. I agree that this is dumb. So, a bit of explanation. 

These projects, and the other, older example repositories, are like this. They are really collections of examples that formerly were only available on the Cypress website. So they have a "proprietary-ish" approach to licenses. The information is there, but buried.

Current Cypress repos have a license file and/or a EULA obviously located in the repo. We use the readme for instructions, getting started, or an explanation of what's in the repo. However, getting to the EULA or license is now pretty obvious.

Thanks for the feedback. Truly appreciated.

**Comment by oxr463** [comment]
Thank you for the explanation!
