### ISSUE TITLE
Day 38 project works only in non-connectable mode 

### ISSUE THREAD

**Issue by yourskp** [cypresssemiconductorco/PSoC-4-BLE#3]
Problem - Day 38 project will only work in non-connectable advertisement mode and when connectable mode is enabled, the device disconnects immediately after establishing connection.

Root Cause - This is due to a bug in the code where the LFCLK source for PSoC 4 BLE device was not updated to WCO (accurate low frequency clock) and was still running on ILO (highly inaccurate). This caused timing offset in connected mode that resulted in BLE link disconnection.

Temporary Fix - The updated project is at - https://github.com/yourskp/BLE/tree/master/Low_Power_Startup

**Comment by JimTrudeau** [comment]
I am closing this issue as moot.
