### ISSUE TITLE
mesh network node can not broadcast once it transfer a message with address

### ISSUE THREAD

**Issue by wacsy** [cypresssemiconductorco/PSoC-4-BLE#6]
There is no address reset in the button pressing event. So in the beginning, a node can broadcast when the button pressed, but once it transfer a message with an address, then it cannot broadcast anymore. Since the variable received_node_addr and received_node_addr_type are static claimed in GenericEventHandler, the sensor_process.c can not touch they. Am I correct, please? Thanks a lot for any help.

**Comment by JimTrudeau** [comment]
I am closing this issue as moot.
