### ISSUE TITLE
Error in customizer for component "BLE_v1_20" : Loading : (Unable to locate and customize component 'BLE_v1_20' used in schematic 

### ISSUE THREAD

**Issue by duraiswamy** [cypresssemiconductorco/PSoC-4-BLE#8]
Error in customizer for component "BLE_v1_20" : Loading : (Unable to locate and customize component 'BLE_v1_20' used in schematic  .. Unable to find the Ble component

**Comment by optimeaspal** [comment]
I have the same problem and would like to test the example. Is there already a fix for it?

**Comment by tge96** [comment]
Update the component to version 2.1
