### ISSUE TITLE
tmp100 with psoc creator

### ISSUE THREAD

**Issue by duraiswamy** [cypresssemiconductorco/PSoC-4-BLE#9]
I'm newer to the psoc  - I want measure temerature over I2C with a TMP100. Please share some example

**Comment by TomBurg** [comment]
Hi
Sorry, but I’m not using the TMP100 sensor in any of my designs.

Cheers, Tom
Email: thomas.burgmann@stronachgroup.commailto:thomas.burgmann@stronachgroup.com

**Comment by JimTrudeau** [comment]
I am closing this issue as moot.
